#!/usr/bin/env bash

echo "Loading all data..." >&2
weights=()
get_weight_string() {
	{
		emo get-tag "$1" boost count | paste -sd+ | bc
		echo "$1"
	} | paste -d ' ' - -
}
export -f get_weight_string
mapfile -t weights <<< "$(emo list-songs | parallel get_weight_string)"
list="$(printf '%s\n' "${weights[@]}" | cut -d ' ' -f 1)"

generate() {
	ix="$(weighted-choice <<< "$list")"
	echo "add ${weights[$ix]#* }" >&"${nc[1]}"
}

coproc nc (nc "$@")
trap 'pkill -P $$' EXIT

echo "clear" >&"${nc[1]}"
generate

pc=0
while read -ru "${nc[0]}" cmd; do
	case "$cmd" in
		"exit")         exit ;;
		"client mpv status "*) pc="$(sed -En "s|^.*\((.*)%\)|\1|p" <<< "$cmd")" ;;
		"next-is "*)
			((pc >= 80)) && {
				count="$(emo get-tag "$song" count)"
				emo set-tag "$song" count "$((count + 1))"
				echo "Completed $song, count was $count"
			}
			echo "queue" >&"${nc[1]}"
			;;
		"error empty queue")
			generate
			song="${cmd#next-is }"
			;;
	esac
done
