#!/usr/bin/env bash

[ "$1" == "--get-weight" ] && {
	hash="$(emo name-to-hash "$2")"
	dir="$(emo getpaths tags)/$hash"
	echo "$((
		$(tr '\n' ' ' < "$dir/count") +
		$(cat "$dir/boost")
	)) $2"
	exit
}

echo "Loading all data..." >&2
mapfile -t weights <<< "$(emo list-songs | sed -E 's|(.*)|'"$0"' --get-weight "\1"|' | parallel --will-cite)"
list="$(printf '%s\n' "${weights[@]}" | cut -d ' ' -f 1)"

generate() {
	ix="$(weighted-choice <<< "$list")"
	echo "add ${weights[$ix]#* }" >&"${nc[1]}"
}

coproc nc (nc "$@")
trap 'pkill -P $$' EXIT

echo "clear" >&"${nc[1]}"
generate
echo "next" >&"${nc[1]}"

pc=0
while read -ru "${nc[0]}" cmd; do
	case "$cmd" in
		"exit")         exit ;;
		"client mpv "*) pc="$(sed -En "s|^.*\((.*)%\)|\1|p" <<< "$cmd")" ;;
		"next-is "*)
			((pc >= 80)) && {
				count="$(emo get-tag "$song" count)"
				emo set-tag "$song" count "$((count + 1))"
				echo "Completed $song, count was $count"
			}
			generate
			song="${cmd#next-is }"
			;;
	esac
done
