#!/usr/bin/env bash
nc_args=("$@")

song_dir="$(emo getpaths songs)"
coproc nc (nc "${nc_args[@]}")
trap 'pkill -P $$' EXIT

play() {
	{ mpv --input-ipc-server=/tmp/mpvsoc-emo --no-video "$song_dir/$1" >/dev/null; } 2>&1 \
	| while read -rd "$(printf '\r')" line; do
		[ -z "$line" ] && continue
		echo "client mpv ${line#*A: }"
	done | nc "${nc_args[@]}" && echo "next" | nc "${nc_args[@]}"
}

stop() {
	pid="$(pgrep -P "$$" bash)" && pkill -P "$pid"
}

while read -ru "${nc[0]}" cmd; do
	case "$cmd" in
		"exit") exit ;;
		"error empty queue") stop ;;
		"next-is "*)
			stop
			play "${cmd#next-is }" &
			;;
	esac
done
